MVCMahasiswa/Models/DaftarNilai.cs
namespace MVCMahasiswa.Models
{
    public enum IndexNilai
    {
        A,B,C,D,E
    }
    public class DaftarNilai
    {
        public int DaftarNilaiID { get; set; }
        public int MataKuliahID { get; set; }
        public int MahasiswaID { get; set; }
        public IndexNilai? IndexNilai { get; set; }

        public virtual MataKuliah MataKuliah { get; set; }
        public virtual Mahasiswa Mahasiswa { get; set; }
    }
}

MVCMahasiswa/Controllers/DaftarNilaiController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCMahasiswa.DAL;
using MVCMahasiswa.Models;

namespace MVCMahasiswa.Controllers
{
    public class DaftarNilaiController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: DaftarNilai
        public ActionResult Index(string sortOrder, string searchString)
        {           

            var daftarNilais = db.DaftarNilais.Include(d => d.Mahasiswa).Include(d => d.MataKuliah);

            ///sorting////
            ViewBag.currentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.NameMKSortParm = String.IsNullOrEmpty(sortOrder) ? "namemk_desc" : "";
            ViewBag.IndexNilSortParm = String.IsNullOrEmpty(sortOrder) ? "indexnil_desc": "";

            switch (sortOrder)
            {
                case "name_desc":
                    daftarNilais = daftarNilais.OrderByDescending(s => s.Mahasiswa.NamaMahasiswa);
                    break;
                case "namemk_desc":
                    daftarNilais = daftarNilais.OrderByDescending(s => s.MataKuliah.NamaMataKuliah);
                    break;
                case "indexnil_desc":
                    daftarNilais = daftarNilais.OrderByDescending(s => s.IndexNilai);
                    break;
                default:
                    daftarNilais = daftarNilais.OrderBy(s => s.Mahasiswa.NamaMahasiswa);
                    break;
            }
            ///search///
            if (!String.IsNullOrEmpty(searchString))
            {
                daftarNilais = daftarNilais.Where(s => s.Mahasiswa.NamaMahasiswa.Contains(searchString));
            }

            return View(daftarNilais.ToList());
        }

        // GET: DaftarNilai/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaftarNilai daftarNilai = db.DaftarNilais.Find(id);
            if (daftarNilai == null)
            {
                return HttpNotFound();
            }
            return View(daftarNilai);
        }

        // GET: DaftarNilai/Create
        public ActionResult Create()
        {
            ViewBag.MahasiswaID = new SelectList(db.Mahasiswas, "MahasiswaID", "NamaMahasiswa");
            ViewBag.MataKuliahID = new SelectList(db.MataKuliahs, "MataKuliahID", "NamaMataKuliah");
            return View();
        }

        // POST: DaftarNilai/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DaftarNilaiID,MataKuliahID,MahasiswaID,IndexNilai")] DaftarNilai daftarNilai)
        {
            if (ModelState.IsValid)
            {
                db.DaftarNilais.Add(daftarNilai);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.MahasiswaID = new SelectList(db.Mahasiswas, "MahasiswaID", "NamaMahasiswa", daftarNilai.MahasiswaID);
            ViewBag.MataKuliahID = new SelectList(db.MataKuliahs, "MataKuliahID", "NamaMataKuliah", daftarNilai.MataKuliahID);
            return View(daftarNilai);
        }

        // GET: DaftarNilai/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaftarNilai daftarNilai = db.DaftarNilais.Find(id);
            if (daftarNilai == null)
            {
                return HttpNotFound();
            }
            ViewBag.MahasiswaID = new SelectList(db.Mahasiswas, "MahasiswaID", "NamaMahasiswa", daftarNilai.MahasiswaID);
            ViewBag.MataKuliahID = new SelectList(db.MataKuliahs, "MataKuliahID", "NamaMataKuliah", daftarNilai.MataKuliahID);
            return View(daftarNilai);
        }

        // POST: DaftarNilai/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DaftarNilaiID,MataKuliahID,MahasiswaID,IndexNilai")] DaftarNilai daftarNilai)
        {
            if (ModelState.IsValid)
            {
                db.Entry(daftarNilai).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MahasiswaID = new SelectList(db.Mahasiswas, "MahasiswaID", "NamaMahasiswa", daftarNilai.MahasiswaID);
            ViewBag.MataKuliahID = new SelectList(db.MataKuliahs, "MataKuliahID", "NamaMataKuliah", daftarNilai.MataKuliahID);
            return View(daftarNilai);
        }

        // GET: DaftarNilai/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DaftarNilai daftarNilai = db.DaftarNilais.Find(id);
            if (daftarNilai == null)
            {
                return HttpNotFound();
            }
            return View(daftarNilai);
        }

        // POST: DaftarNilai/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DaftarNilai daftarNilai = db.DaftarNilais.Find(id);
            db.DaftarNilais.Remove(daftarNilai);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCMahasiswa/Views/DaftarNilai/Create.cshtml
@model MVCMahasiswa.Models.DaftarNilai

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DaftarNilai</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MataKuliahID, "MataKuliahID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MataKuliahID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MataKuliahID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MahasiswaID, "MahasiswaID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MahasiswaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MahasiswaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IndexNilai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.IndexNilai, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IndexNilai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCMahasiswa/Views/DaftarNilai/Delete.cshtml
@model MVCMahasiswa.Models.DaftarNilai

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DaftarNilai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mahasiswa.NamaMahasiswa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mahasiswa.NamaMahasiswa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MataKuliah.NamaMataKuliah)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MataKuliah.NamaMataKuliah)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IndexNilai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IndexNilai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCMahasiswa/Views/DaftarNilai/Details.cshtml
@model MVCMahasiswa.Models.DaftarNilai

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DaftarNilai</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mahasiswa.NamaMahasiswa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mahasiswa.NamaMahasiswa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MataKuliah.NamaMataKuliah)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MataKuliah.NamaMataKuliah)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IndexNilai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IndexNilai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DaftarNilaiID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCMahasiswa/Views/DaftarNilai/Edit.cshtml
@model MVCMahasiswa.Models.DaftarNilai

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DaftarNilai</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DaftarNilaiID)

        <div class="form-group">
            @Html.LabelFor(model => model.MataKuliahID, "Mata Kuliah", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MataKuliahID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MataKuliahID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MahasiswaID, "Mahasiswa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MahasiswaID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MahasiswaID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IndexNilai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.IndexNilai, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IndexNilai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCMahasiswa/Views/DaftarNilai/Index.cshtml
@model IEnumerable<MVCMahasiswa.Models.DaftarNilai>
@{
    ViewBag.Title = "Index";
}

<h2>Daftar Nilai</h2>
@if (User.Identity.IsAuthenticated)
{
    

<p>
    @Html.ActionLink("Create New", "Create")
</p>
using (Html.BeginForm("Index", "DaftarNilai", FormMethod.Get))
{
    <p>
        Cari Nama: @Html.TextBox("searchString", ViewBag.currentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Mahasiswa.NamaMahasiswa)*@
            @Html.ActionLink("Nama Mahasiswa", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            @*Html.DisplayNameFor(model => model.MataKuliah.NamaMataKuliah)*@
            @Html.ActionLink("Nama Mata Kuliah", "Index", new { sortOrder = ViewBag.NameMKSortParm })
        </th>
        <th>
            @*Html.DisplayNameFor(model => model.IndexNilai)*@
            @Html.ActionLink("Index Nilai", "Index", new { sortOrder = ViewBag.IndexNilSortParm })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Mahasiswa.NamaMahasiswa)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MataKuliah.NamaMataKuliah)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IndexNilai)
        </td>
        @if (User.Identity.IsAuthenticated)
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.DaftarNilaiID }) |
                @Html.ActionLink("Details", "Details", new { id = item.DaftarNilaiID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.DaftarNilaiID })
            </td>
        }
        
    </tr>
}

</table>
} else {
 <h3>Please Login to access</h3>

}