MVCMahasiswa/Models/MataKuliah.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCMahasiswa.Models
{
    public class MataKuliah
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int MataKuliahID { get; set; }

        [Display(Name = "Nama Mata kuliah")]
        public string NamaMataKuliah { get; set; }

        public int Bobot { get; set; }

        public virtual ICollection<DaftarNilai> DaftarNilais { get; set; }
    }
}

MVCMahasiswa/Controllers/MataKuliahController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCMahasiswa.DAL;
using MVCMahasiswa.Models;
using MVCMahasiswa.CustomFilters;

namespace MVCMahasiswa.Controllers
{
    public class MataKuliahController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: MataKuliah
        public ActionResult Index(string searchString, string sortOrder)
        {
            var matakuliah = from s in db.MataKuliahs
                             select s;

            ///sort///
            ViewBag.currentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            
            switch (sortOrder)
            {
                case "name_desc":
                    matakuliah = matakuliah.OrderByDescending(s => s.NamaMataKuliah);
                    break;
                default:
                    matakuliah = matakuliah.OrderBy(s => s.NamaMataKuliah);
                    break;
            }

            ////search////
            

            if (!String.IsNullOrEmpty(searchString))
            {
                matakuliah = matakuliah.Where(s => s.NamaMataKuliah.Contains(searchString));
            }

            return View(matakuliah.ToList());
            //return View(db.MataKuliahs.ToList());
        }

        // GET: MataKuliah/Details/5
        [AuthLog(Roles="Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MataKuliah mataKuliah = db.MataKuliahs.Find(id);
            if (mataKuliah == null)
            {
                return HttpNotFound();
            }
            return View(mataKuliah);
        }

        // GET: MataKuliah/Create
        [AuthLog(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: MataKuliah/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MataKuliahID,NamaMataKuliah,Bobot")] MataKuliah mataKuliah)
        {
            if (ModelState.IsValid)
            {
                db.MataKuliahs.Add(mataKuliah);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mataKuliah);
        }

        // GET: MataKuliah/Edit/5
        [AuthLog(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MataKuliah mataKuliah = db.MataKuliahs.Find(id);
            if (mataKuliah == null)
            {
                return HttpNotFound();
            }
            return View(mataKuliah);
        }

        // POST: MataKuliah/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MataKuliahID,NamaMataKuliah,Bobot")] MataKuliah mataKuliah)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mataKuliah).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mataKuliah);
        }

        // GET: MataKuliah/Delete/5
        [AuthLog(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MataKuliah mataKuliah = db.MataKuliahs.Find(id);
            if (mataKuliah == null)
            {
                return HttpNotFound();
            }
            return View(mataKuliah);
        }

        // POST: MataKuliah/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MataKuliah mataKuliah = db.MataKuliahs.Find(id);
            db.MataKuliahs.Remove(mataKuliah);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCMahasiswa/Views/MataKuliah/Create.cshtml
@model MVCMahasiswa.Models.MataKuliah

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MataKuliah</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MataKuliahID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MataKuliahID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MataKuliahID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NamaMataKuliah, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamaMataKuliah, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NamaMataKuliah, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bobot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bobot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bobot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCMahasiswa/Views/MataKuliah/Delete.cshtml
@model MVCMahasiswa.Models.MataKuliah

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MataKuliah</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NamaMataKuliah)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamaMataKuliah)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bobot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bobot)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCMahasiswa/Views/MataKuliah/Details.cshtml
@model MVCMahasiswa.Models.MataKuliah

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MataKuliah</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NamaMataKuliah)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NamaMataKuliah)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bobot)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bobot)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MataKuliahID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCMahasiswa/Views/MataKuliah/Edit.cshtml
@model MVCMahasiswa.Models.MataKuliah

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MataKuliah</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MataKuliahID)

        <div class="form-group">
            @Html.LabelFor(model => model.NamaMataKuliah, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NamaMataKuliah, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NamaMataKuliah, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bobot, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bobot, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bobot, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCMahasiswa/Views/MataKuliah/Index.cshtml
@model IEnumerable<MVCMahasiswa.Models.MataKuliah>

@{
    ViewBag.Title = "Daftar Mata Kuliah";
}

<h2>Daftar Mata Kuliah</h2>
@if ((User.Identity.IsAuthenticated) && (this.User.IsInRole("Admin")))
{    
<p>
    @Html.ActionLink("Create New", "Create")
</p>
}


@using (Html.BeginForm("Index", "MataKuliah", FormMethod.Get))
{
    <p>
        Cari Nama: @Html.TextBox("searchString", ViewBag.currentFilter as string)
        <input type="submit" value="Search" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @*Html.DisplayNameFor(model => model.NamaMataKuliah)*@
            @Html.ActionLink("Nama Mata Kuliah", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bobot)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NamaMataKuliah)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bobot)
        </td>
        @if (User.Identity.IsAuthenticated)
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MataKuliahID }) |
                @Html.ActionLink("Details", "Details", new { id = item.MataKuliahID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MataKuliahID })
            </td>
        }        
    </tr>
}

</table>