MVCMahasiswa/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MVCMahasiswa.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using MVCMahasiswa.CustomFilters;

namespace MVCMahasiswa.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }


        // GET: Role
        //[AuthLog(Roles="Admin")]
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        //create new role
        //[AuthLog(Roles = "Admin")]
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }

        //create new role
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVCMahasiswa/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>

@using (Html.BeginForm())
{
    <table id="tbrole">
        <tr>
            <td class="c">New Role Name:</td>
            <td class="c">
                @Html.EditorFor(m => m.Name)
            </td>
        </tr>
    </table>
    <input type="submit" value="Create" />
}

MVCMahasiswa/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Available Roles</h2>
@Html.ActionLink("Create Role", "Create", "Role")
<style type="text/css" >
    #tbrole,.c{
        border:double;
    }
</style>

<table id="tbrole">
    <tr>
        <td class="c">Role Name</td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="c">
                @item.Name
            </td>
        </tr>
    }    
</table>